name: ROS 2 CI

on:
  push:
  pull_request:

jobs:
  ros2-ci:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        ros_distro: [humble]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ROS 2 CI
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          ros_distro: ${{ matrix.ros_distro }}
          package_name: |
            my_cpp_pkg
            my_python_pkg
          target_ws: .
